# Generated by Django 4.2 on 2023-05-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
