# Generated by Django 4.2 on 2023-05-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_remove_frame_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=models.FileField(upload_to='frames/'),
        ),
    ]
