# Generated by Django 4.2 on 2023-05-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_alter_frame_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=models.FileField(upload_to='images/frames/'),
        ),
    ]
