# Generated by Django 4.2 on 2023-05-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_alter_prediction_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frame',
        ),
    ]
